name: Release Snapshot to Sonatype

on:
  push:
  release:
    types: [published]

jobs:
  release_snapshot_sonatype:
    # if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 8
          cache: sbt
      - name: Release Snapshot to Sonatype
        run: |
          # VERSION=$(git describe --tags | cut -f2 -d"@")
          VERSION=0.0.0-2022-02-17-SNAPSHOT
          if [[ ${VERSION:0:1} == "v" ]] ; then
            VERSION=${VERSION:1}
          fi
          if [[ ${VERSION: -9} != "-SNAPSHOT" ]] ; then
            echo "Version must end in -SNAPSHOT. Adding -SNAPSHOT suffix"
            VERSION="$VERSION-SNAPSHOT"
          fi
          echo $PGP_SECRET | base64 --decode | gpg --batch --import
          export GPG_TTY=$(tty)
          echo "Releasing version $VERSION Sonatype as snapshot"
          yes | sbt -DRELEASE_TYPE=snapshot -DCAPI_TEST_KEY=$CAPI_TEST_KEY "clean" "release cross release-version $VERSION with-defaults"
        env:
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          CAPI_TEST_KEY: ${{ secrets.CAPI_TEST_KEY }}
