name: 'Publish Release'
on:
  release:
    types: [published]
jobs:
  sbt_release:
    runs-on: ubuntu-latest
    steps:
      - uses: guardian/actions-sbt-release@v3
        with:
          pgpSecret: ${{ secrets.PGP_SECRET }}
          pgpPassphrase: ${{ secrets.PGP_PASSPHRASE }}
          sonatypeUsername: ${{ secrets.SONATYPE_USERNAME }}
          sonatypePassword: ${{ secrets.SONATYPE_PASSWORD }}
          isSnapshot: ${{ github.event.release.prerelease }}
          CAPI_TEST_KEY: ${{ secrets.CAPI_TEST_KEY }}
